language: node_js

node_js:
  - '10'

addons:
  chrome: stable

before_install:
  - npm install -D coveralls

script:
  - npm run test -- --code-coverage --configuration=ci
  - npm run e2e -- --configuration=ci

after_success:
  - cat ./coverage/ngrx-todo/lcov.info | ./node_modules/coveralls/bin/coveralls.js

before_deploy:
  - npm run build -- --prod

deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
  skip_cleanup: true
